"""
api/events.py — Event endpoints.

An Event is a named container for one or more performances.
Examples: "Bonnaroo 2009" (festival), "Fall 1989 Tour" (tour run).

Promoted to a full dimension 2026-09-01 (Ryan). It had list / search / detail /
create / update and nothing else: no delete, no photos, no recordings on the
detail payload, and no page in the app at all — the only way to touch an event
was the ingest form's autocomplete. It is now the fifth dimension alongside
Venue, Performer, Artist and Genre, and carries the same surface as the rest.

Routes:
  GET    /api/events/            — list events (q= for search)
  GET    /api/events/search      — name autocomplete (q=)
  GET    /api/events/<id>        — detail + performances + recordings + photos
  POST   /api/events/            — create
  PUT    /api/events/<id>        — update
  DELETE /api/events/<id>        — delete (409 while performances reference it)
  …plus the five standard photo routes, generated by the shared registrar.
"""

from flask import Blueprint, request, jsonify, current_app
from flask_login import login_required
from sqlalchemy import func, or_

from app.extensions import db
from app.models.event import Event
from app.models.event_image import EventImage
from app.models.venue import Venue
from app.models.performance import Performance
from app.models.recording import Recording
from app.utils.format import format_partial_date
from app.utils.serialize import recording_row
from app.utils.ingest import _sanitize_path
from app.utils import entity_images as ei
from app.api.system import require_library

bp = Blueprint("events", __name__)


# ── Photos ───────────────────────────────────────────────────────────────────
# Same parallel-table / shared-behaviour arrangement as Venue and Artist. See
# app/utils/entity_images.py::register_image_routes.

_IMG_URL = "/api/events/images"


def _event_images_dir(event):
    return ei.entity_images_dir(current_app.config["LIBRARY_ROOT"],
                                "_events", event.name, _sanitize_path)


ei.register_image_routes(
    bp, parent_model=Event, image_model=EventImage, url_prefix=_IMG_URL,
    images_dir_for=_event_images_dir,
    login_required=login_required, require_library=require_library,
)


# ── Autocomplete (must come before /<int:event_id>) ───────────────────────────

@bp.route("/search")
@login_required
def search_events():
    """Name autocomplete for the ingest form. Returns [{id, name}]."""
    q = request.args.get("q", "").strip()
    if not q:
        return jsonify([])
    like = f"%{q}%"
    rows = (
        db.session.query(Event.id, Event.name)
        .filter(Event.name.ilike(like))
        .order_by(Event.name)
        .limit(12)
        .all()
    )
    return jsonify([{"id": r.id, "name": r.name} for r in rows])


# ── List ──────────────────────────────────────────────────────────────────────

@bp.route("/")
@login_required
def list_events():
    q = request.args.get("q", "").strip()
    query = db.session.query(Event)
    if q:
        like = f"%{q}%"
        # City too, matching how /api/venues/ searches — "everything I have from
        # Manchester" is the same question whether it is asked of a venue or a
        # festival, and answering it for one but not the other is arbitrary.
        query = query.filter(or_(Event.name.ilike(like), Event.city.ilike(like)))

    # No limit. It was 200, copied from the shape list_venues had before
    # 2026-08-30 — and that cap is exactly the bug that silently truncated the
    # Venues nav list mid-alphabet. Ordered by name, a 200-row cut is invisible:
    # nothing says anything is missing. Removed here before it could bite twice.
    events = query.order_by(Event.name).all()

    # Grouped counts + primary photo, not one lazy-load per row — the index page
    # and the sidebar both call this.
    perf_counts = dict(
        db.session.query(Performance.event_id, func.count(Performance.id))
        .filter(Performance.event_id.isnot(None))
        .group_by(Performance.event_id).all()
    )
    rec_counts = dict(
        db.session.query(Performance.event_id, func.count(Recording.id))
        .join(Recording, Recording.performance_id == Performance.id)
        .filter(Performance.event_id.isnot(None))
        .group_by(Performance.event_id).all()
    )
    image_ids = {}
    for eid, iid, _p in (
        db.session.query(EventImage.event_id, EventImage.id, EventImage.is_primary)
        .order_by(EventImage.event_id, EventImage.is_primary.desc(),
                  EventImage.sort_order, EventImage.id).all()
    ):
        image_ids.setdefault(eid, iid)

    return jsonify([
        {**_event_summary(e, perf_counts.get(e.id, 0)),
         "recording_count": rec_counts.get(e.id, 0),
         "image_id":        image_ids.get(e.id)}
        for e in events
    ])


# ── Detail ────────────────────────────────────────────────────────────────────

@bp.route("/<int:event_id>")
@login_required
def get_event(event_id):
    e = db.session.get(Event, event_id)
    if not e:
        return jsonify({"error": "Not found"}), 404

    perfs = sorted(
        e.performances,
        key=lambda p: (p.start_year or 0, p.start_month or 0, p.start_day or 0),
    )

    # One row per Recording at this event, chronological. Same serializer the
    # Venue page uses, so the frontend renders both with one row builder.
    recordings = [recording_row(r) for p in perfs for r in p.recordings]

    return jsonify({
        **_event_summary(e),
        "notes": e.notes,
        "venue": {"id": e.venue.id, "name": e.venue.name} if e.venue else None,
        "performances": [
            {
                "id":        p.id,
                # ⚠ This said `p.artist.name` until 2026-09-01 and had never
                # been exercised — Performance has no `artist` relationship
                # (it is `performer`; the 2026-07-11 remodel renamed the old
                # act-Artist to Performer and this line was missed). Any
                # request for an event with a performance attached raised
                # AttributeError. Nothing called it, because there was no
                # Event page. There is one now.
                "performer":    p.performer.name if p.performer else None,
                "performer_id": p.performer_id,
                "date":      format_partial_date(p.start_year, p.start_month, p.start_day),
                "stage":     p.stage,
                "venue":     p.venue.name if p.venue else None,
                "recording_count": len(p.recordings),
            }
            for p in perfs
        ],
        "recordings":      recordings,
        "recording_count": len(recordings),
        "has_image":       bool(e.images),
        "images":          [ei.image_payload(i, _IMG_URL) for i in e.images],
    })


# ── Create ────────────────────────────────────────────────────────────────────

@bp.route("/", methods=["POST"])
@login_required
def create_event():
    data = request.get_json() or {}
    name = (data.get("name") or "").strip()
    if not name:
        return jsonify({"error": "name is required"}), 400

    # Prevent exact-name duplicates
    existing = db.session.query(Event).filter(
        func.lower(Event.name) == name.lower()
    ).first()
    if existing:
        return jsonify({"error": "Event already exists", "id": existing.id}), 409

    venue_id = data.get("venue_id") or None
    if venue_id and not db.session.get(Venue, int(venue_id)):
        return jsonify({"error": "venue not found"}), 400

    e = Event(
        name        = name,
        venue_id    = int(venue_id) if venue_id else None,
        city        = (data.get("city")    or "").strip() or None,
        state       = (data.get("state")   or "").strip() or None,
        country     = (data.get("country") or "").strip() or None,
        start_year  = _int_or_none(data.get("start_year")),
        start_month = _int_or_none(data.get("start_month")),
        start_day   = _int_or_none(data.get("start_day")),
        end_year    = _int_or_none(data.get("end_year")),
        end_month   = _int_or_none(data.get("end_month")),
        end_day     = _int_or_none(data.get("end_day")),
        notes       = (data.get("notes") or "").strip() or None,
    )
    db.session.add(e)
    db.session.commit()
    return jsonify({"id": e.id, "name": e.name}), 201


# ── Update ────────────────────────────────────────────────────────────────────

@bp.route("/<int:event_id>", methods=["PUT"])
@login_required
def update_event(event_id):
    e = db.session.get(Event, event_id)
    if not e:
        return jsonify({"error": "Not found"}), 404

    data = request.get_json() or {}

    if "name" in data:
        e.name = (data["name"] or "").strip() or e.name
    if "venue_id" in data:
        e.venue_id = int(data["venue_id"]) if data["venue_id"] else None
    if "city" in data:
        e.city = (data["city"] or "").strip() or None
    if "state" in data:
        e.state = (data["state"] or "").strip() or None
    if "country" in data:
        e.country = (data["country"] or "").strip() or None
    for f in ("start_year", "start_month", "start_day",
              "end_year", "end_month", "end_day"):
        if f in data:
            setattr(e, f, _int_or_none(data[f]))
    if "notes" in data:
        e.notes = (data["notes"] or "").strip() or None

    db.session.commit()
    return jsonify(_event_summary(e))


# ── Delete ────────────────────────────────────────────────────────────────────

@bp.route("/<int:event_id>", methods=["DELETE"])
@login_required
def delete_event(event_id):
    """
    Delete an event. Refuses while performances still point at it.

    Same guard as Venue, Artist, Genre and Collection deletes — and the same
    reasoning: `performance.event_id` is nullable, so cascading would silently
    orphan real shows to remove a label. Unlinking is a decision, so it is the
    caller's to make explicitly.
    """
    e = db.session.get(Event, event_id)
    if not e:
        return jsonify({"error": "Not found"}), 404
    n = len(e.performances)
    if n:
        return jsonify({"error": f"Event has {n} performance(s) — reassign or "
                                 "delete those recordings first."}), 409
    db.session.delete(e)
    db.session.commit()
    return jsonify({"ok": True})


# ── Helpers ───────────────────────────────────────────────────────────────────

def _int_or_none(v):
    """
    Partial dates arrive from a text field, so '' and '1989' both turn up.

    int('') raises and would 500 a save whose only sin is a cleared box. The
    columns are nullable on purpose — a year with no month is a normal state
    for this corpus, not incomplete input.
    """
    if v is None or v == "":
        return None
    try:
        return int(v)
    except (TypeError, ValueError):
        return None


def _event_summary(e, performance_count=None):
    """
    The shared shape. `performance_count` is passed IN by the list endpoint
    from a grouped query — computing it here as len(e.performances) would fire
    one lazy load per row and undo the point of the grouped counts above.
    """
    return {
        "id":               e.id,
        "name":             e.name,
        "city":             e.city,
        "state":            e.state,
        "country":          e.country,
        "venue_id":         e.venue_id,
        "venue_name":       e.venue.name if e.venue else None,
        "start_year":       e.start_year,
        "start_month":      e.start_month,
        "start_day":        e.start_day,
        "end_year":         e.end_year,
        "end_month":        e.end_month,
        "end_day":          e.end_day,
        "performance_count": (len(e.performances) if performance_count is None
                              else performance_count),
    }
