"""
api/venues.py — Venue endpoints.

Routes:
  GET  /api/venues/        — list venues (q= for search)
  GET  /api/venues/<id>    — venue detail + performances
  POST /api/venues/        — create venue
  PUT  /api/venues/<id>    — update venue
"""

from flask import Blueprint, request, jsonify, current_app
from flask_login import login_required
from sqlalchemy import or_, func

from app.extensions import db
from app.models.venue import Venue
from app.models.venue_image import VenueImage
from app.models.performance import Performance
from app.models.recording import Recording
from app.utils.serialize import recording_row
from app.utils.ingest import _sanitize_path
from app.utils import entity_images as ei
from app.api.system import require_library

bp = Blueprint("venues", __name__)


@bp.route("/")
@login_required
def list_venues():
    q = request.args.get("q", "").strip()
    query = db.session.query(Venue)
    if q:
        like = f"%{q}%"
        query = query.filter(
            or_(Venue.name.ilike(like), Venue.city.ilike(like), Venue.state.ilike(like))
        )
    # No limit — list_performers/list_artists/list_genres don't cap theirs
    # either, and the sidebar's whole point is showing the complete index.
    # This one WAS capped at 200 and it bit: alphabetically past "L" is
    # exactly where a 200-row cut lands once a library has more than 200
    # venues, so the Venues nav list silently stopped mid-alphabet with no
    # sign anything was missing (Ryan, 2026-08-30).
    venues = query.order_by(Venue.name).all()

    # Counts and the primary-photo id come from two grouped queries rather than
    # `len(v.performances)` per row (2026-09-01, for the Venues index page).
    # The old shape was one lazy-load per venue and then, for the index tiles,
    # would have been a second per venue for images — on a 500-venue library
    # that is a thousand round trips to draw one page. Same fix as
    # /all-recordings got on 2026-08-24, same reason.
    perf_counts = dict(
        db.session.query(Performance.venue_id, func.count(Performance.id))
        .filter(Performance.venue_id.isnot(None))
        .group_by(Performance.venue_id).all()
    )
    rec_counts = dict(
        db.session.query(Performance.venue_id, func.count(Recording.id))
        .join(Recording, Recording.performance_id == Performance.id)
        .filter(Performance.venue_id.isnot(None))
        .group_by(Performance.venue_id).all()
    )
    # Primary first, oldest as the fallback — matches primary_for()'s ordering,
    # so a venue whose primary was just deleted still shows a face.
    image_ids = {}
    for vid, iid, is_primary in (
        db.session.query(VenueImage.venue_id, VenueImage.id, VenueImage.is_primary)
        .order_by(VenueImage.venue_id, VenueImage.is_primary.desc(),
                  VenueImage.sort_order, VenueImage.id).all()
    ):
        image_ids.setdefault(vid, iid)

    return jsonify([
        {
            "id":                v.id,
            "name":              v.name,
            "city":              v.city,
            "state":             v.state,
            "country":           v.country,
            "performance_count": perf_counts.get(v.id, 0),
            "recording_count":   rec_counts.get(v.id, 0),
            "image_id":          image_ids.get(v.id),
        }
        for v in venues
    ])


@bp.route("/<int:venue_id>")
@login_required
def get_venue(venue_id):
    v = db.session.get(Venue, venue_id)
    if not v:
        return jsonify({"error": "Not found"}), 404

    perfs = sorted(
        v.performances,
        key=lambda p: (p.start_year or 0, p.start_month or 0, p.start_day or 0),
    )

    # One row per Recording at this venue (two tapers of one show = two rows),
    # chronological old→new. Recordings within a performance keep their own order.
    recordings = [recording_row(r) for p in perfs for r in p.recordings]

    return jsonify({
        "id":                v.id,
        "name":              v.name,
        "city":              v.city,
        "state":             v.state,
        "country":           v.country,
        "bio":               v.bio,
        "performance_count": len(v.performances),
        "recording_count":   len(recordings),
        "recordings":        recordings,
        "has_image":         bool(v.images),
        "images":            [ei.image_payload(i, _IMG_URL) for i in v.images],
    })


# ── Photos (2026-08-07; routes moved to the shared registrar 2026-09-01) ────
# Parallel table to performer_image, shared behaviour via utils/entity_images.
# Files live under LIBRARY_ROOT/_venues/<sanitized name>/_images — the `_venues`
# prefix keeps them out of the performer namespace, because a venue and an act
# can share a name ("Fillmore") and two entities writing one folder is a
# collision waiting to happen.
#
# The five route declarations that used to sit here are now generated by
# ei.register_image_routes(), which Artist and Event also use. The endpoint
# names it produces (list_venue_images, upload_venue_images, serve_venue_image,
# make_venue_image_primary, delete_venue_image) are the same ones the
# hand-written versions had, so url_for() callers and tests are unaffected.

_IMG_URL = "/api/venues/images"


def _venue_images_dir(venue):
    return ei.entity_images_dir(current_app.config["LIBRARY_ROOT"],
                                "_venues", venue.name, _sanitize_path)


ei.register_image_routes(
    bp, parent_model=Venue, image_model=VenueImage, url_prefix=_IMG_URL,
    images_dir_for=_venue_images_dir,
    login_required=login_required, require_library=require_library,
)


@bp.route("/", methods=["POST"])
@login_required
def create_venue():
    data = request.get_json()
    if not data.get("name", "").strip():
        return jsonify({"error": "name is required"}), 400
    v = Venue(
        name    = data["name"].strip(),
        city    = data.get("city", "").strip() or None,
        state   = data.get("state", "").strip() or None,
        country = data.get("country", "").strip() or None,
        bio     = data.get("bio", "").strip() or None,
    )
    db.session.add(v)
    db.session.commit()
    return jsonify({"id": v.id, "name": v.name}), 201


@bp.route("/<int:venue_id>", methods=["PUT"])
@login_required
def update_venue(venue_id):
    v = db.session.get(Venue, venue_id)
    if not v:
        return jsonify({"error": "Not found"}), 404
    data = request.get_json()
    for field in ["name", "city", "state", "country", "bio"]:
        if field in data:
            setattr(v, field, data[field])
    db.session.commit()
    return jsonify({"id": v.id})


@bp.route("/<int:venue_id>", methods=["DELETE"])
@login_required
def delete_venue(venue_id):
    """Delete a venue. Refuses while performances still reference it."""
    v = db.session.get(Venue, venue_id)
    if not v:
        return jsonify({"error": "Not found"}), 404
    n = len(v.performances)
    if n:
        return jsonify({"error": f"Venue has {n} performance(s) — reassign or "
                                 "delete those recordings first."}), 409
    db.session.delete(v)
    db.session.commit()
    return jsonify({"ok": True})
