"""
app/utils/checksums.py — Fingerprint file parsing + checksum verification.

Background (researched 2026-07-13 against the etree.org wiki and shntool's own
docs, since getting this wrong would be worse than not having the feature):

  .ffp  A "FLAC Fingerprint" is generated by `metaflac --show-md5sum` — it is
        NOT a checksum of the encoded .flac file. It is the MD5 signature FLAC
        itself stores internally, computed over the *decoded* audio samples
        only. Renaming the file or editing tags never changes it. Verifying
        it means reading that signature back out of the file (mutagen already
        exposes it) — no decoding required, so this is fast.

  .st5  shntool's own checksum. Per the etree.org FlacFingerprint page:
        "The flac fingerprint should be identical to what is sometimes called
        a 'shntool md5', which is a checksum calculated on just the music
        data" — i.e. by design, an .st5 value for a given track should equal
        that track's .ffp value. We verify it the same way as ffp. Treated as
        best-effort: shntool is documented to not produce st5 for 24-bit/96k
        FLAC, and we can't rule out edge-case algorithm differences we simply
        don't have visibility into. A mismatch here is worth a second look,
        not an alarm.

  .md5  A conventional whole-file MD5 (hashlib over the raw file bytes,
        including headers/tags). Unlike ffp/st5, this WILL change if Flux (or
        anything else) rewrites the file's Vorbis tags — that's expected
        behavior, not corruption, and the UI should say so.

Nothing here reads audio via librosa/soundfile — ffp/st5 verification only
needs mutagen's already-parsed STREAMINFO, and md5 only needs raw bytes.
"""

import hashlib
import os
import re
import unicodedata

from mutagen.flac import FLAC

_HEX32 = re.compile(r"\b[0-9a-fA-F]{32}\b")
_AUDIO_EXT = re.compile(r"\.(?:flac|wav|shn|mp3)$", re.IGNORECASE)
# One or more leading "[tool]" markers, as shntool emits in .st5 files.
_LEADING_BRACKET = re.compile(r"^(?:\s*\[[^\]]*\]\s*)+")

# Preference order when a folder has more than one fingerprint file covering
# the same track — only one type can occupy a track's checksum_status slot,
# so ties need a winner. ffp first (best-understood format, verifies audio
# content, immune to tag edits), then md5 (whole-file, but simple and well
# understood), then st5 last (verified here by inference from shntool/etree
# docs rather than a spec Ryan's ever actually vetted — see module docstring;
# it shouldn't out-rank a type either of you trusts more). Used by both
# api/ingest.py (_do_confirm) and api/recordings.py (verify_checksums).
FINGERPRINT_TYPE_PRIORITY = {"ffp": 0, "md5": 1, "st5": 2}


def flac_md5_signature(abs_path):
    """The FLAC file's own internal MD5-of-decoded-audio signature, as
    lowercase hex. None if the file can't be read or the encoder never
    stored one (an all-zero signature is valid FLAC for 'not computed')."""
    try:
        info = FLAC(abs_path).info
    except Exception:
        return None
    sig = getattr(info, "md5_signature", 0)
    if not sig:
        return None
    return format(sig, "032x")


def file_md5(abs_path, chunk_size=1024 * 1024):
    """Whole-file MD5, lowercase hex. None if the file can't be read."""
    h = hashlib.md5()
    try:
        with open(abs_path, "rb") as fh:
            for chunk in iter(lambda: fh.read(chunk_size), b""):
                h.update(chunk)
    except OSError:
        return None
    return h.hexdigest()


def parse_checksum_file(content):
    """
    Tolerant line parser for .ffp / .md5 / .st5 text. Community tools don't
    agree on a single delimiter (colon, tab, double-space, "*"-prefixed
    filename...), so rather than commit to one, every line is scanned for a
    32-hex-char token (the checksum) and an audio-filename-shaped token
    (flac/wav/shn/mp3). A line with a hex token but no recognizable filename
    still contributes a checksum — match_entries_to_tracks() falls back to
    positional matching when nothing in the file has a filename.

    Returns: [{"filename": str|None, "checksum": "32charhex"}, ...] in
    file order. Lines with no hex token (blank lines, headers, comments) are
    skipped.
    """
    entries = []
    for line in (content or "").splitlines():
        line = line.strip()
        if not line:
            continue
        hex_match = _HEX32.search(line)
        if not hex_match:
            continue
        checksum = hex_match.group(0).lower()
        # Filename candidate = whatever's left on the line once the hash is
        # cut out, trimmed of the usual separators (*, :, tabs/runs of
        # spaces). Track filenames routinely contain spaces themselves, so
        # this can't be a single-token regex — it has to take "the rest of
        # the line" and just check whether it looks like an audio filename.
        rest = (line[:hex_match.start()] + " " + line[hex_match.end():]).strip(" \t*:")
        # Strip LEADING bracketed tool markers (2026-08-02). shntool writes
        #     <hash>  [shntool]  Track 01.flac
        # and without this the filename came out as "[shntool]  Track 01.flac",
        # which matched no track — every one of the 474 .st5 files in the
        # library parsed its hashes correctly and then matched zero tracks.
        #
        # LEADING only, deliberately: a track legitimately named
        # "Track 01 [live].flac" must keep its brackets. The marker's position
        # is what identifies it, not the brackets themselves.
        rest = _LEADING_BRACKET.sub("", rest).strip(" \t*:")
        filename = os.path.basename(rest) if rest and _AUDIO_EXT.search(rest) else None
        entries.append({"filename": filename, "checksum": checksum})
    return entries


def _norm_key(name):
    """
    NFC-normalize a filename before using it as a comparison key.

    macOS/APFS commonly hands back decomposed (NFD) unicode for filenames
    with accented characters (os.walk, scan_folder), while fingerprint text
    files — usually generated on Windows/Linux, or just typed/pasted — are
    typically composed (NFC). "Lucía" (NFC) and "Lucía" (NFD) are visually
    identical but byte-for-byte different, so a bare string comparison
    silently fails to match. Same failure class the quality-scoring tool hit
    joining disk folder names to DB grades (2026-07-27) — see
    `Context Library/Listening Quality — v2 Results.md`, "Two bugs found."
    Without this, a recording with an accented track title could ingest with
    every checksum unmatched and no error, because match_entries_to_tracks()
    fails closed (leaves rows unmatched) rather than raising.
    """
    return unicodedata.normalize("NFC", name).lower() if name else None


class ChecksumMatchProxy:
    """
    Stand-in for a Track during fingerprint matching, shared between
    app.api.ingest._do_confirm (step 9, at ingest time) and
    app.api.recordings.verify_checksums (post-ingest re-validate/backfill).

    match_entries_to_tracks() matches by reading `.file_path` / `.track_number`
    off whatever it's given. A fingerprint file lists ORIGINAL filenames --
    which may differ from Track.file_path whenever the recording was renamed
    on ingest (compute_audio_rename_map/move_to_library) or later (Rename
    Files) -- so this proxy presents the ORIGINAL filename to the matcher
    while `.real` routes a successful match back to the actual Track.
    """
    def __init__(self, real_track, original_filename):
        self.real          = real_track
        self.file_path     = original_filename
        self.track_number  = real_track.track_number


def match_entries_to_tracks(entries, tracks):
    """
    Match parsed fingerprint entries to Track rows. Prefers filename matching
    (exact basename, then filename-stem, both case-insensitive and unicode-
    normalized — a fingerprint generated against the original .shn/.wav set
    will still match the .flac track by stem). Falls back to positional (file
    order == track_number order) ONLY when none of the entries carry a
    filename at all and the counts line up exactly — anything less certain
    is left unmatched rather than guessed.

    Note (2026-07-14): library audio is renamed on ingest whenever the
    active naming scheme calls for it (compute_audio_rename_map/
    move_to_library in app.utils.ingest — keep mode's 'original' scheme
    renames nothing), so a fingerprint file can list ORIGINAL scanned
    filenames while Track.file_path holds a new name — filename matching
    alone won't always connect
    them. Confirm-time matching (app.api.ingest._do_confirm) handles this
    with a proxy that presents each track's original filename here instead
    of its real one; this function's matching logic is unchanged and stays
    strict on purpose — see [[project_checksum_format_preference]].

    Returns: {track: checksum} for whatever could be confidently matched.
    """
    if not entries or not tracks:
        return {}

    def _stem(name):
        return os.path.splitext(name)[0].lower() if name else None

    by_basename = {_norm_key(os.path.basename(t.file_path)): t for t in tracks}
    by_stem     = {_norm_key(_stem(t.file_path)): t for t in tracks}

    matched = {}
    named_entries = [e for e in entries if e["filename"]]

    for e in named_entries:
        key = _norm_key(e["filename"])
        track = by_basename.get(key) or by_stem.get(_norm_key(_stem(e["filename"])))
        if track and track not in matched:
            matched[track] = e["checksum"]

    if not named_entries and len(entries) == len(tracks):
        ordered_tracks = sorted(tracks, key=lambda t: t.track_number)
        for track, e in zip(ordered_tracks, entries):
            matched[track] = e["checksum"]

    return matched


def discover_fingerprint_files(folder_abs_path):
    """
    Walk an already-ingested recording's library folder for fingerprint files
    that were copied in with it but never parsed — either because it was
    ingested before this feature existed, or the folder held one the initial
    scan missed. `move_to_library` copies the entire source tree (not just
    audio), so anything that shipped alongside the show is still sitting
    right there. Reuses the same marker-based detection as scan_folder() so a
    recording processed this way is classified identically to a fresh ingest.

    Returns: [{"type", "filename", "rel_path"}, ...]
    """
    # Imported lazily to avoid a module-load-order dependency between the two
    # utils modules — app/api/ingest.py already imports both directly.
    from app.utils.ingest import AUDIO_EXTENSIONS, fingerprint_type_for_file

    found = []
    for dirpath, _dirnames, filenames in os.walk(folder_abs_path):
        for fname in filenames:
            ext = os.path.splitext(fname)[1].lower()
            if ext in AUDIO_EXTENSIONS:
                continue
            full = os.path.join(dirpath, fname)
            # fingerprint_type_for_file also sniffs CONTENT for unmarked .txt
            # files (2026-08-02), so a checksum list named after the show is
            # discovered here too — previously it was invisible to both paths.
            fp_type = fingerprint_type_for_file(full, fname.lower())
            if fp_type:
                found.append({
                    "type":     fp_type,
                    "filename": fname,
                    "rel_path": os.path.relpath(full, folder_abs_path),
                })
    return found


class _ScanTrackProxy:
    """
    Stand-in for a Track so match_entries_to_tracks() works BEFORE ingest.

    That matcher reads `.file_path` / `.track_number` off whatever it is given
    — it does not care that a real Track row exists. Presenting scanned files
    through this proxy means triage and confirm run the identical matching
    logic, rather than triage growing a second, subtly-different matcher that
    could disagree with what ingest will actually do.
    """
    def __init__(self, audio_file):
        self.file_path    = audio_file.get("rel_path") or audio_file["filename"]
        self.track_number = audio_file.get("index") or 0
        self.audio        = audio_file


# FFP and ST5 compare against the FLAC's own STREAMINFO md5 signature, which
# mutagen reads out of the header — microseconds, no decode, no full read.
# MD5 hashes the WHOLE FILE, so verifying a 400 MB show means pulling 400 MB
# off the NAS. At triage, across a queue, that is the difference between a
# 2-second card and a multi-minute one.
CHEAP_FP_TYPES = ("ffp", "st5")


def audit_folder_fingerprints(folder_path, audio_files, deep=False):
    """
    Pre-ingest fingerprint audit for the triage card (2026-08-02).

    Answers "do the checksums shipped with this show actually verify?" before
    anything is copied into the library — the point at which a bad tape is
    cheapest to reject.

    `deep=False` verifies only CHEAP_FP_TYPES (header reads). MD5 files are
    parsed, matched and reported, but their tracks come back "unverified"
    pending an explicit deep pass — Ryan's call, so the queue stays fast and
    the expensive check is spent on the shows worth spending it on.

    audio_files: scan_folder()["audio_files"] shape.
    Returns {"files": [...], "summary": {...}, "deep": bool}.
    """
    from app.utils.ingest import scan_folder  # noqa: F401  (import cycle guard)

    proxies = [_ScanTrackProxy(a) for a in (audio_files or [])]
    files, summary = [], {"match": 0, "mismatch": 0, "unverified": 0,
                          "unmatched": 0, "files": 0, "pending_deep": 0}

    for fp in discover_fingerprint_files(folder_path):
        fp_type  = fp["type"]
        rel_path = fp["rel_path"]
        abs_path = os.path.join(folder_path, rel_path)
        try:
            with open(abs_path, "r", encoding="utf-8", errors="replace") as fh:
                content = fh.read()
        except OSError as e:
            files.append({"filename": fp["filename"], "rel_path": rel_path,
                          "type": fp_type, "error": str(e), "tracks": []})
            continue

        entries = parse_checksum_file(content)

        # Same disc-scoping rule as _do_confirm: a fingerprint file nested in
        # CD1/ lists names scoped to that disc, and bare names like "01.flac"
        # collide across discs. Restrict candidates to that subdir, falling
        # back to everything if the scoping finds nothing.
        fp_dir = os.path.dirname(rel_path).replace(os.sep, "/")
        candidates = proxies
        if fp_dir:
            scoped = [p for p in proxies
                      if os.path.dirname(p.file_path).replace(os.sep, "/") == fp_dir]
            if scoped:
                candidates = scoped

        matched   = match_entries_to_tracks(entries, candidates)
        cheap     = fp_type in CHEAP_FP_TYPES
        will_test = cheap or deep

        tracks = []
        for proxy in candidates:
            expected = matched.get(proxy)
            if expected is None:
                status = "unmatched"
            elif not will_test:
                status = "pending"
            else:
                status = verify_track_checksum(
                    proxy.audio.get("path") or os.path.join(folder_path, proxy.file_path),
                    fp_type, expected)
            tracks.append({
                "filename": os.path.basename(proxy.file_path),
                "expected": expected,
                "status":   status,
            })
            key = {"unmatched": "unmatched", "pending": "pending_deep"}.get(status, status)
            summary[key] = summary.get(key, 0) + 1

        # Entries in the file that matched no audio file at all — a checksum
        # list longer than the folder means tracks are missing, which is worth
        # saying out loud rather than quietly ignoring.
        orphan_entries = max(0, len(entries) - len(matched))

        files.append({
            "filename":       fp["filename"],
            "rel_path":       rel_path,
            "type":           fp_type,
            "entry_count":    len(entries),
            "matched_count":  len(matched),
            "orphan_entries": orphan_entries,
            "verified":       will_test,
            "tracks":         tracks,
        })
        summary["files"] += 1

    # One headline per folder. "mismatch" outranks everything — a failed
    # checksum is the single fact this panel exists to surface.
    if not files:
        verdict = "none"
    elif summary["mismatch"]:
        verdict = "mismatch"
    elif summary["match"] and not summary["unmatched"] and not summary["pending_deep"]:
        verdict = "verified"
    elif summary["match"]:
        verdict = "partial"
    else:
        verdict = "unverified"

    return {"files": files, "summary": summary, "verdict": verdict, "deep": bool(deep)}


def verify_track_checksum(abs_path, fp_type, expected_checksum):
    """Recompute a track's actual checksum and compare. Returns one of
    'match' / 'mismatch' / 'unverified' (couldn't compute — missing file,
    unreadable FLAC, or no expected value to compare against)."""
    if not expected_checksum:
        return "unverified"
    if fp_type in ("ffp", "st5"):
        actual = flac_md5_signature(abs_path)
    elif fp_type == "md5":
        actual = file_md5(abs_path)
    else:
        actual = None
    if not actual:
        return "unverified"
    return "match" if actual.lower() == expected_checksum.strip().lower() else "mismatch"
